# Generated by Django 4.2.6 on 2023-11-02 02:40

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('tamaño', models.CharField(choices=[('XS', ' MuyPequeño'), ('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Gigante')], max_length=15)),
                ('descripcion', models.TextField()),
                ('raza', models.CharField(max_length=100)),
                ('tiene_cartilla', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_de_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(related_name='usuarios', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='usuarios', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferencia_tamaño', models.CharField(choices=[('XS', ' MuyPequeño'), ('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Gigante')], max_length=15)),
                ('preferencia_raza', models.CharField(max_length=100)),
                ('preferencia_edad_min', models.IntegerField()),
                ('preferencia_edad_max', models.IntegerField()),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_match', models.DateTimeField(auto_now_add=True)),
                ('mascota1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascota1', to='main_app.mascota')),
                ('mascota2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascota2', to='main_app.mascota')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.usuario'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='main_app.mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='matched_with', to='main_app.mascota'),
        ),
        migrations.CreateModel(
            name='ImagenMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_1', models.ImageField(upload_to='mascota_imagenes/')),
                ('imagen_2', models.ImageField(upload_to='mascota_imagenes/')),
                ('imagen_3', models.ImageField(upload_to='mascota_imagenes/')),
                ('imagen_4', models.ImageField(upload_to='mascota_imagenes/')),
                ('imagen_5', models.ImageField(upload_to='mascota_imagenes/')),
                ('imagen_6', models.ImageField(upload_to='mascota_imagenes/')),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_mensaje', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='main_app.usuario')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.match')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitente', to='main_app.usuario')),
            ],
        ),
    ]
