# Generated by Django 4.2.6 on 2023-11-09 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mascota",
            name="matches",
        ),
        migrations.RemoveField(
            model_name="preferencias",
            name="mascota",
        ),
        migrations.AddField(
            model_name="preferencias",
            name="usuario",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
