# Generated by Django 4.2.6 on 2023-11-21 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_usuario_fotografia_identificacion_usuario_verificado"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="bloqueado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="bloqueado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="usuarios_bloqueados",
            field=models.ManyToManyField(
                related_name="usuarios_bloqueadores", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Reportes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.TextField()),
                ("fecha_reporte", models.DateTimeField(auto_now_add=True)),
                (
                    "reportador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_reportado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_recibidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
