# Generated by Django 4.2.6 on 2023-11-23 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_chat_bloqueado_match_bloqueado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='peso',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(choices=[('Bulldog francés', 'Bulldog francés'), ('Labrador retriever', 'Labrador retriever'), ('Golden retriever', 'Golden retriever'), ('Pastor alemán', 'Pastor alemán'), ('Caniche', 'Caniche'), ('Bulldog', 'Bulldog'), ('Rottweiler', 'Rottweiler'), ('Beagle', 'Beagle'), ('Salchicha', 'Salchicha'), ('Braco alemán de pelo corto', 'Braco alemán de pelo corto'), ('Corgi galés de Pembroke', 'Corgi galés de Pembroke'), ('Pastor australiano', 'Pastor australiano'), ('Yorkshire terrier', 'Yorkshire terrier'), ('Cavalier King Charles spaniel', 'Cavalier King Charles spaniel'), ('Doberman pinscher', 'Doberman pinscher'), ('Boxer', 'Boxer'), ('Schnauzer miniatura', 'Schnauzer miniatura'), ('Cane corso', 'Cane corso'), ('Gran danés', 'Gran danés'), ('Shih Tzu', 'Shih Tzu'), ('Husky siberiano', 'Husky siberiano'), ('Chihuahua', 'Chihuahua'), ('Solovino', 'Solovino')], max_length=100),
        ),
    ]
