# Generated by Django 4.2.6 on 2023-11-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_alter_mascota_edad_alter_mascota_peso"),
    ]

    operations = [
        migrations.AddField(
            model_name="mascota",
            name="adopcion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mascota",
            name="facebook_mascota",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mascota",
            name="instagram_mascota",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mascota",
            name="tiktok_mascota",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mascota",
            name="twitter_mascota",
            field=models.URLField(blank=True, null=True),
        ),
    ]
